services:
  - type: web
    name: bird-diversity-ranking
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: EBIRD_API_KEY
        sync: false
